site_name: Turnroot Editor Documentation
nav:
  - Home: 'index.md'
  - Getting Started:
    - Quick Start (Cloud): 'getting-started/quick-start.md'
    - Register and login (Cloud): 'getting-started/register-and-login.md'
    - Local Installation: 'getting-started/local-installation.md'
    - First Hour with Turnroot: 'getting-started/your-first-hour-in-the-turnroot-editor.md'
  - Navigating:
    - Editor Basics: 'editor-basics.md'
    - The Sidebar: 'sidebar.md'
    - Main Toolbar: 'main-toolbar.md'
    - Status Bar: 'status-bar.md'
    - Editor Settings: 'editor-settings.md'
    - Tabs: 'tabs.md'
    - Secondary Sidebars: 'secondary-sidebars.md'
    - Keyboard Shortcuts: 'keyboard-shortcuts.md'
  - Editors:
    - Unit Editor: 'editors/unit-editor.md'
    - Project Editor: 'editors/project-editor.md'
  - Assets:
    - Asset Management: 'asset-management.md'
    - Import: 'import.md'
  - Best Practices:
    - Naming Stuff: 'naming-stuff.md'
    - Referring to Existing Game Data: 'referring-to-existing-game-data.md'
    - Finding Assets: 'finding-assets.md'
    - Playtesting: 'playtesting.md'
  - Collaboration:
    - Working with a Team: 'collaboration/working-with-a-team.md'
    - Sharing a Project: 'collaboration/sharing-a-project.md'
    - Shared Version Control: 'collaboration/version-control.md'
    - Roles: 'collaboration/roles.md'
  - Test and Build:
    - Check for Issues: 'check-for-issues.md'
    - Test Something: 'test-something.md'
    - Build: 'build.md'
    - Publish: 'publish.md'
  - File Management:
    - Where are my files?: 'where-are-my-files.md'
    - Saving: 'saving.md'
    - Autosave: 'autosave.md'
    - Overall Structure: 'project-structure.md'
    - Planning for Success: 'planning-for-success.md'
    - Linking Files: 'linking-files.md'
  - Technical Details:
    - Changelog: 'technical-details/changelog.md'
    - Roadmap: 'technical-details/roadmap.md'
    - Structure: 'technical-details/structure.md'
  - Community:
    - Joining the Community: 'community/joining-the-community.md'
    - Sharing Your Work: 'community/sharing-your-work.md'
    - Sharing Assets: 'community/sharing-assets.md'
    - Using the Forum: 'community/using-the-forum.md'
    - Reporting Issues: 'community/reporting-issues.md'
    - Contributing: 'community/contributing.md'

theme: readthedocs