site_name: Turnroot Editor Documentation
nav:
  - Home: 'index.md'
  - Getting Started:
    - Quick Start (Cloud): 'quick-start.md'
    - Local Installation: 'local-installation.md'
    - First Hour with Turnroot: 'first-hour.md'
  - Navigating the Editor:
    - Editor Basics: 'editor-basics.md'
    - The Sidebar: 'sidebar.md'
    - Main Toolbar: 'main-toolbar.md'
    - Status Bar: 'status-bar.md'
    - Editor Settings: 'editor-settings.md'
  - File Management:
    - Where are my files?: 'where-are-my-files.md'
    - Autosave: 'autosave.md'
    - Overall Structure: 'project-structure.md'
    - Planning for Success: 'planning-for-success.md'
  - Technical Details:
    - Changelog: 'technical-details/changelog.md'
theme: readthedocs